language: python

install: make install-test

cache: pip

script:
  - export PYTHONPATH=`pwd`
  - make lint
  - pytest

jobs:
  include:
    - stage: test
      python: 3.6
    - stage: test
      python: 3.7
      dist: xenial
      sudo: true
    - stage: code coverage
      python: 3.7
      dist: xenial
      sudo: true
      install:
        - make install-test
        - pip install coveralls
      script:
        - export PYTHONPATH=`pwd`
        - pytest
        - coveralls
    - stage: PyPI Upload
      python: 3.7
      dist: xenial
      sudo: true
      script: echo "Uploading packages to PyPI"
      deploy:
        provider: pypi
        user: cuenca
        password:
          secure: "XnhF8HjBscS9ctT852VqiYo1aMqnV//XMlHTCH8RiV9Mn/8zcfgWZYP3QUKHS17Pq1uSOnE5ZRYa1v7z+uireFsg8noQuLyR3UcFF1Sc2cO7C2lBDeI3qJCsz6BVIniM754xXOtgDCsBIH9NB86nxKq1q17nIPv3pNY/bMKy0yKbS05dnmLmlFJWuHcYSwYSEu0wQQsEuCy6cp8Ar5VVOWO6rPtzMIHz9OIQI0KjOK55E15UiBKku2r4wO96Vthwfpk8qO3a0KYOoDIR80WuuOg46oc6ZxyUhr0vcZBPI31VDAmnA9G5S6xLQ4QDqKMPiwiwg/zPDK1Ib4ZPO+cM6aWkdw7qjpLiKsgPBsUNd/WwZNMHEZDLhrod2Xc6OUKNCdkfEAiL7kKAMYxSjmxfEIamGvBRlPUwOtMRsq/L8iRUuXCA4ZU69UmPMLeVxRTSegC4L6Ay/ugc4DWCxPhXze4b5fCeavU1hoqCOvuBzJEVTFd11mSkPacvrQu/gv1anpO1056xPs+4xS48qOY2Vwe8ehZuZCWPMlOb1y5BD8sqxJ8Att2R3Cg6AzBeLsk2ngmg9dPMJCcAxx2dyMQrp9xgFs+p9AS55T+GU65p2XXawZUxmqUXyh/MKuRT82j659tBi61ufbE5OxI7BJQI0w+/wNNKYl0F1nIaPLazD9I="

        on:
          tags: true
        distributions: sdist bdist_wheel
